// LOCALHOST
### Get all users
GET http://localhost:8080/user

### Get a single user
GET http://localhost:8080/user/lomolo

### Create a user
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "username": "lomolo2",
    "password": "Word!123Pass",
    "name": "John Doe"
}

### Update a user by username
PUT http://localhost:8080/user/lomolo HTTP/1.1
content-type: application/json

{
    "password":"Wasspord123!",
    "name": "Dan Collins"
}

### Delete a user by username
DELETE http://localhost:8080/user/adigolfer01 HTTP/1.1

### Create a jornal entry
POST http://localhost:8080/jornal HTTP/1.1
content-type: application/json

{
    "username": "adigolfer01",
    "entry": "I skipped work today and watched star wars.",
    "entryDate": "2022-06-19"
}

// PRODUCTION Deploy
### Get all users
GET https://cse341-personal-project/user

### Get a single user
GET https://cse341-personal-project/user/lomolo

### Create a user
POST https://cse341-personal-project/user HTTP/1.1
content-type: application/json

{
    "username": "lomolo2",
    "password": "Word!123Pass",
    "name": "John Doe"
}

### Update a user by username
PUT https://cse341-personal-project/user/lomolo HTTP/1.1
content-type: application/json

{
    "password":"Wasspord123!",
    "name": "Dan Collins"
}

### Delete a user by username
DELETE https://cse341-personal-project/user/adigolfer01 HTTP/1.1

### Create a jornal entry
POST https://cse341-personal-project/jornal HTTP/1.1
content-type: application/json

{
    "username": "adigolfer01",
    "entry": "I skipped work today and watched star wars.",
    "entryDate": "2022-06-19"
}